package-as: Kui_Nameplates

manual-changelog:
    filename: changelog
    markup-type: markdown

enable-nolib-creation:
    no

move-folders:
    Kui_Nameplates/Kui_Media: Kui_Media
    Kui_Nameplates/Kui_Nameplates_Core: Kui_Nameplates_Core
    Kui_Nameplates/Kui_Nameplates_Core_Config: Kui_Nameplates_Core_Config
    Kui_Nameplates/Kui_Nameplates: Kui_Nameplates

ignore:
    - Kui_Nameplates/lib/LibClassicDurations
    - Kui_Nameplates/lib/LibClassicCasterino
    - Kui_Nameplates/lib/LibThreatClassic2
    - .gitignore
    - .luacheckrc
    - .externals
    - changelog
    - README.md
    - examples
    - dev
