language: minimal

addons:
    apt:
        packages:
        - luarocks

install: luarocks install --local luacheck

script:
    - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g classic -m .pkgmeta-classic.yml
    - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g bcc -m .pkgmeta-classic.yml
    - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g wrath -m .pkgmeta-classic.yml
    - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g retail -m .pkgmeta.yml

notifications:
    email:
        on_success: never
        on_failure: always
